Unauthorized: /api/v1/switch/switch_run_command/
<<<<<<< HEAD
Unauthorized: /api/v1/switch-command/
Unauthorized: /api/v1/switch-command/
Unauthorized: /api/v1/switch/
Unauthorized: /api/v1/switch-command/
Unauthorized: /api/v1/contact/portmap/
Unauthorized: /api/v1/switch/
Unauthorized: /api/v1/dslam/
=======
Unauthorized: /api/v1/switch/switch_run_command/
Internal Server Error: /api/v1/dslam/load_dslam_ports/
Method Not Allowed: /api/v1/dslam/load_dslam_ports/
Internal Server Error: /api/v1/dslam/load_dslam_ports
Traceback (most recent call last):
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 113, in __call__
    response = self.process_request(request)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/middleware/common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/middleware/common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:2080/api/v1/dslam/load_dslam_ports/?dslam_id=40&slot_count=10&port_count=10 (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
Internal Server Error: /api/v1/dslam/load_dslam_ports/
Internal Server Error: /api/v1/dslam/load_dslam_ports/
Internal Server Error: /api/v1/dslam/load_dslam_ports/
Not Found: /favicon.ico
Not Found: /favicon.ico
Method Not Allowed: /api/v1/router/router-runCommand/
Method Not Allowed: /api/v1/router/router-runCommand/
Not Found: /api/v1/router/router-runCommand/
Method Not Allowed: /api/v1/router/router-runCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Not Found: /favicon.ico
Unauthorized: /api/v1/switch/switch_run_command/
Unauthorized: /api/v1/dslam/load_dslam_ports/
Not Found: /favicon.ico
Not Found: /favicon.ico
Unauthorized: /api/v1/switch/get_backup_files_name/
Method Not Allowed: /api/v1/switch/get_backup_files_name/
Unauthorized: /api/v1/switch/get_backup_files_name/
>>>>>>> 7f250673d7f388c149dce86fb5fc9d4f100d6c28
Unauthorized: /api/v1/switch/download_backup_file/
Not Found: /favicon.ico
Unauthorized: /api/v1/switch/download_backup_file/
Unauthorized: /api/v1/switch/download_backup_file/
Internal Server Error: /api/v1/switch/download_backup_file/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'str'>`
Unauthorized: /api/v1/switch/get_backup_files_name/
