Forbidden: /api/v1/dslamport/events/
Forbidden: /api/v1/dslam/events/
Internal Server Error: /api/v1/dslam/get_interface_traffic_input/
Unauthorized: /api/v1/switch-command/
Unauthorized: /api/v1/switch/
Unauthorized: /api/v1/switch/
Unauthorized: /api/v1/router-command/
Unauthorized: /api/v1/switch/
Unauthorized: /api/v1/switch/read_switch_backup_error_files_name/
Unauthorized: /api/v1/switch/
Unauthorized: /api/v1/switch/read_switch_backup_error_files_name/
Unauthorized: /api/v1/router/
Unauthorized: /api/v1/router-command/read_router_backup_error_files_name/
Unauthorized: /api/v1/switch/
Unauthorized: /api/v1/router/
Unauthorized: /api/v1/switch/
Forbidden: /api/v1/dslam/events/
Forbidden: /api/v1/dslamport/events/
Unauthorized: /api/v1/switch/
Unauthorized: /api/v1/router/
Forbidden: /api/v1/dslam/events/
Forbidden: /api/v1/dslamport/events/
Internal Server Error: /api/v1/dslam/get_interface_traffic_input/
Internal Server Error: /api/v1/dslam/get_interface_traffic_input/
Unauthorized: /api/v1/router/
Unauthorized: /api/v1/router/
Unauthorized: /api/v1/router/
Unauthorized: /api/v1/router/
Unauthorized: /api/v1/router/
Unauthorized: /api/v1/router/
Unauthorized: /api/v1/router/
Unauthorized: /api/v1/router/
Unauthorized: /api/v1/switch/
Unauthorized: /api/v1/router/download_router_backup_file/
Unauthorized: /api/v1/router/
Unauthorized: /api/v1/router/
Unauthorized: /api/v1/switch/
Unauthorized: /api/v1/router/
Unauthorized: /api/v1/switch/
Unauthorized: /api/v1/router/
Unauthorized: /api/v1/router/
Unauthorized: /api/v1/router-command/
Internal Server Error: /api/v1/dslam/get_interface_traffic_input/
Internal Server Error: /api/v1/dslam/get_interface_traffic_input/
Internal Server Error: /api/v1/dslam/get_interface_traffic_input/
Internal Server Error: /api/v1/dslam/get_interface_traffic_input/
Unauthorized: /api/v1/router/
Internal Server Error: /api/v1/dslam/get_interface_traffic_input/
Unauthorized: /api/v1/router/
Unauthorized: /api/v1/switch/
Unauthorized: /api/v1/router/
Unauthorized: /api/v1/switch/
Unauthorized: /api/v1/router/
Internal Server Error: /api/v1/dslam/get_interface_traffic_input/
Internal Server Error: /api/v1/dslam/get_interface_traffic_input/
Internal Server Error: /api/v1/dslam/get_interface_traffic_input/
Internal Server Error: /api/v1/dslam/get_interface_traffic_input/
Internal Server Error: /api/v1/dslam/get_interface_traffic_input/
Internal Server Error: /api/v1/dslam/get_interface_traffic_input/
Internal Server Error: /api/v1/dslam/get_interface_traffic_input/
Internal Server Error: /api/v1/dslam/get_interface_traffic_input/
Internal Server Error: /api/v1/dslam/get_interface_traffic_input/
Unauthorized: /api/v1/router/get_router_backup_files_name/
Unauthorized: /api/v1/router/
Unauthorized: /api/v1/dslam/
Unauthorized: /api/v1/router/
Unauthorized: /api/v1/users/login/
Unauthorized: /api/v1/users/login/
Internal Server Error: /api/v1/router-command/router_run_command/
Internal Server Error: /api/v1/router-command/router_run_command/
Unauthorized: /api/v1/router-command/router_run_command/
Unauthorized: /api/v1/router-command/router_run_command/
Unauthorized: /api/v1/dslam/
Unauthorized: /api/v1/switch/
Unauthorized: /api/v1/router/
Unauthorized: /api/v1/router/get_router_backup_files_name/
Unauthorized: /api/v1/dslam/get_interface_traffic_input/
Unauthorized: /api/v1/dslam/get_dslams_packet_loss_count/
Unauthorized: /api/v1/dslamport/events/
Unauthorized: /api/v1/dslam/events/
Unauthorized: /api/v1/dslam/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/dslam/
Unauthorized: /api/v1/dslam/
Unauthorized: /api/v1/dslam/
Internal Server Error: /api/v1/dslam/icmp/command/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/portmanv3/portman_web/dslam/views.py", line 1166, in post
    result = utility.run_icmp_command(dslam_id, icmp_type, params)
  File "/opt/portmanv3/portman_web/dslam/utility.py", line 61, in run_icmp_command
    return c.run_icmp_command(dslam_id, icmp_type, params)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 821, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 695, in _request
    response = self._run_request(request)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 730, in _run_request
    response = self.__transport.request(
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1153, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 413, in single_request
    self.send_content(connection, request_body)
  File "/usr/local/lib/python3.8/dist-packages/jsonrpclib/jsonrpc.py", line 476, in send_content
    connection.endheaders()
  File "/usr/lib/python3.8/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1007, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 947, in send
    self.connect()
<<<<<<< HEAD
  File "/usr/lib/python3.8/http/client.py", line 918, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
Internal Server Error: /api/v1/dslam/get_interface_traffic_input/
Not Found: /api/v1/router/
Not Found: /api/v1/router/
Not Found: /api/v1/router/
Not Found: /api/v1/router/
Not Found: /api/v1/router/
Forbidden: /api/v1/dslam/events/
Forbidden: /api/v1/dslamport/events/
Internal Server Error: /api/v1/dslam/get_interface_traffic_input/
Unauthorized: /api/v1/router/
Unauthorized: /api/v1/router/
Not Found: /api/v1/router/
Not Found: /api/v1/router/
Not Found: /api/v1/router/
Not Found: /api/v1/router/
Not Found: /api/v1/router/
Not Found: /api/v1/router/
Not Found: /api/v1/router/
Not Found: /api/v1/router/
Not Found: /api/v1/router/
Not Found: /api/v1/router/
Not Found: /api/v1/router/
Not Found: /api/v1/router/
Not Found: /api/v1/router/
=======
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not connect to server: Connection refused
	Is the server running on host "5.202.129.160" and accepting
	TCP/IP connections on port 5432?

Unauthorized: /api/v1/switch/command/
Not Found: /api/v1/switch/command/
Not Found: /api/v1/switch/command/
Internal Server Error: /api/v1/switch-command/
Traceback (most recent call last):
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/mixins.py", line 45, in list
    serializer = self.get_serializer(queryset, many=True)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/generics.py", line 110, in get_serializer
    return serializer_class(*args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 121, in __new__
    return cls.many_init(*args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 146, in many_init
    child_serializer = cls(*args, **kwargs)
  File "/opt/portmanv3/portman_web/switch/serializers.py", line 33, in __init__
    super(SwitchSerializer, self).__init__(*args, **kwargs)
TypeError: super(type, obj): obj must be an instance or subtype of type
Not Found: /api/v1/switch/command/
Not Found: /api/v1/switch/command/
Not Found: /api/v1/switch/command/
Not Found: /api/v1/switch/command/
Not Found: /api/v1/switch/command/
Not Found: /api/v1/switch/command/
Not Found: /api/v1/switch/command/
Not Found: /api/v1/switch/command/
Not Found: /api/v1/switch/command/
Internal Server Error: /api/v1/switch-command/
Traceback (most recent call last):
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/mixins.py", line 45, in list
    serializer = self.get_serializer(queryset, many=True)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/generics.py", line 110, in get_serializer
    return serializer_class(*args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 121, in __new__
    return cls.many_init(*args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 146, in many_init
    child_serializer = cls(*args, **kwargs)
  File "/opt/portmanv3/portman_web/switch/serializers.py", line 33, in __init__
    super(SwitchSerializer, self).__init__(*args, **kwargs)
TypeError: super(type, obj): obj must be an instance or subtype of type
Internal Server Error: /api/v1/switch-command/
Traceback (most recent call last):
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/mixins.py", line 45, in list
    serializer = self.get_serializer(queryset, many=True)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/generics.py", line 110, in get_serializer
    return serializer_class(*args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 121, in __new__
    return cls.many_init(*args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 146, in many_init
    child_serializer = cls(*args, **kwargs)
  File "/opt/portmanv3/portman_web/switch/serializers.py", line 33, in __init__
    super(SwitchSerializer, self).__init__(*args, **kwargs)
TypeError: super(type, obj): obj must be an instance or subtype of type
Not Found: /api/v1/switch/command/
Not Found: /api/v1/switch/command/
Not Found: /api/v1/switch/command/
Not Found: /api/v1/contact/portmap
Not Found: /api/v1/switch/command/
Not Found: /api/v1/switch/command/
Not Found: /api/v1/switch/command/
Not Found: /api/v1/switch/command/
Not Found: /api/v1/switch/command/
Not Found: /api/v1/switch/command/
Internal Server Error: /api/v1/command2/
Traceback (most recent call last):
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/mixins.py", line 45, in list
    serializer = self.get_serializer(queryset, many=True)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/generics.py", line 110, in get_serializer
    return serializer_class(*args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 121, in __new__
    return cls.many_init(*args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 146, in many_init
    child_serializer = cls(*args, **kwargs)
  File "/opt/portmanv3/portman_web/switch/serializers.py", line 33, in __init__
    super(SwitchSerializer, self).__init__(*args, **kwargs)
TypeError: super(type, obj): obj must be an instance or subtype of type
Not Found: /api/v1/command2
Internal Server Error: /api/v1/switch-command/
Traceback (most recent call last):
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/mixins.py", line 45, in list
    serializer = self.get_serializer(queryset, many=True)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/generics.py", line 110, in get_serializer
    return serializer_class(*args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 121, in __new__
    return cls.many_init(*args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 146, in many_init
    child_serializer = cls(*args, **kwargs)
  File "/opt/portmanv3/portman_web/switch/serializers.py", line 33, in __init__
    super(SwitchSerializer, self).__init__(*args, **kwargs)
TypeError: super(type, obj): obj must be an instance or subtype of type
Internal Server Error: /api/v1/switch-command/
Traceback (most recent call last):
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 457, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 97, in get_attribute
    instance = getattr(instance, attr)
AttributeError: 'SwitchCommand' object has no attribute 'device_ip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 745, in data
    ret = super().data
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 663, in to_representation
    return [
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 664, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 502, in to_representation
    attribute = field.get_attribute(instance)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 490, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `device_ip` on serializer `SwitchCommandSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `SwitchCommand` instance.
Original exception text was: 'SwitchCommand' object has no attribute 'device_ip'.
Internal Server Error: /api/v1/switch-command/
Traceback (most recent call last):
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 457, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 97, in get_attribute
    instance = getattr(instance, attr)
AttributeError: 'SwitchCommand' object has no attribute 'device_ip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 745, in data
    ret = super().data
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 663, in to_representation
    return [
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 664, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 502, in to_representation
    attribute = field.get_attribute(instance)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 490, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `device_ip` on serializer `SwitchCommandSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `SwitchCommand` instance.
Original exception text was: 'SwitchCommand' object has no attribute 'device_ip'.
Internal Server Error: /api/v1/switch-command/
Traceback (most recent call last):
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 745, in data
    ret = super().data
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 663, in to_representation
    return [
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 664, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 500, in to_representation
    for field in fields:
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 361, in _readable_fields
    for field in self.fields.values():
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 349, in fields
    for key, value in self.get_fields().items():
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 1053, in get_fields
    field_class, field_kwargs = self.build_field(
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 1199, in build_field
    return self.build_unknown_field(field_name, model_class)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 1317, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `switch_command_description` is not valid for model `Switch`.
Internal Server Error: /api/v1/switch-command/
Traceback (most recent call last):
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 745, in data
    ret = super().data
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 663, in to_representation
    return [
TypeError: 'SwitchCommand' object is not iterable
Bad Request: /
Bad Request: /favicon.ico
Bad Request: /admin/
Unauthorized: /api/v1/switch/swich_run_command/
Method Not Allowed: /api/v1/switch/switch_run_command/
Not Found: /favicon.ico
Unauthorized: /api/v1/switch/switch_run_command/
Unauthorized: /api/v1/switch/switch_run_command/
Internal Server Error: /api/v1/dslam/load_dslam_ports/
Method Not Allowed: /api/v1/dslam/load_dslam_ports/
Internal Server Error: /api/v1/dslam/load_dslam_ports
Traceback (most recent call last):
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 113, in __call__
    response = self.process_request(request)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/middleware/common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/middleware/common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:2080/api/v1/dslam/load_dslam_ports/?dslam_id=40&slot_count=10&port_count=10 (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
Internal Server Error: /api/v1/dslam/load_dslam_ports/
Internal Server Error: /api/v1/dslam/load_dslam_ports/
Internal Server Error: /api/v1/dslam/load_dslam_ports/
Not Found: /favicon.ico
Not Found: /favicon.ico
Method Not Allowed: /api/v1/router/router-runCommand/
Method Not Allowed: /api/v1/router/router-runCommand/
Not Found: /api/v1/router/router-runCommand/
Method Not Allowed: /api/v1/router/router-runCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Internal Server Error: /api/v1/router/routerRunCommand/
Not Found: /favicon.ico
Unauthorized: /api/v1/switch/switch_run_command/
Unauthorized: /api/v1/dslam/load_dslam_ports/
Not Found: /favicon.ico
Not Found: /favicon.ico
Unauthorized: /api/v1/switch/get_backup_files_name/
Method Not Allowed: /api/v1/switch/get_backup_files_name/
Unauthorized: /api/v1/switch/get_backup_files_name/
Internal Server Error: /api/v1/switch/download_backup_file/
Traceback (most recent call last):
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'str'>`
Internal Server Error: /api/v1/switch/download_backup_file/
Traceback (most recent call last):
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'str'>`
Not Found: /
Not Found: /favicon.ico
Not Found: /favicon.ico
Internal Server Error: /api/v1/router-command/
Traceback (most recent call last):
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 745, in data
    ret = super().data
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 663, in to_representation
    return [
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 664, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 500, in to_representation
    for field in fields:
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 361, in _readable_fields
    for field in self.fields.values():
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 349, in fields
    for key, value in self.get_fields().items():
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 1053, in get_fields
    field_class, field_kwargs = self.build_field(
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 1199, in build_field
    return self.build_unknown_field(field_name, model_class)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 1317, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `switch_command_description` is not valid for model `RouterCommand`.
Internal Server Error: /api/v1/router-command/router_run_command/
Internal Server Error: /api/v1/router-command/router_run_command/
Internal Server Error: /api/v1/router-command/router_run_command/
Internal Server Error: /api/v1/router-command/router_run_command/
Internal Server Error: /api/v1/router-command/router_run_command/
Internal Server Error: /api/v1/router-command/router_run_command/
Internal Server Error: /api/v1/router-command/router_run_command/
Internal Server Error: /api/v1/router-command/router_run_command/
Internal Server Error: /api/v1/router-command/router_run_command/
Internal Server Error: /api/v1/router-command/router_run_command/
Internal Server Error: /api/v1/router/get_router_backup_files_name
Traceback (most recent call last):
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 113, in __call__
    response = self.process_request(request)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/middleware/common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/middleware/common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:2080/api/v1/router/get_router_backup_files_name/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
Internal Server Error: /api/v1/router-command/router_run_command/
Internal Server Error: /api/v1/router-command/router_run_command/
Internal Server Error: /api/v1/router-command/router_run_command/
Internal Server Error: /api/v1/router-command/router_run_command/
Internal Server Error: /api/v1/router-command/router_run_command/
Internal Server Error: /api/v1/router-command/router_run_command/
Internal Server Error: /api/v1/router-command/router_run_command/
Internal Server Error: /api/v1/router-command/router_run_command/
Internal Server Error: /api/v1/router-command/router_run_command/
Internal Server Error: /api/v1/router-command/router_run_command/
Method Not Allowed: /api/v1/router/routerRunCommand/
Method Not Allowed: /api/v1/router/routerRunCommand/
Method Not Allowed: /api/v1/router/routerRunCommand/
Method Not Allowed: /api/v1/router-command/routerRunCommand/
Method Not Allowed: /api/v1/router-command/routerRunCommand/
Method Not Allowed: /api/v1/router-command/routerRunCommand/
Method Not Allowed: /api/v1/router-command/routerRunCommand/
Not Found: /api/v1/router-command/routerRunCommand/
Internal Server Error: /api/v1/router-command/router_run_command/
Internal Server Error: /api/v1/router-command/router_run_command/
Internal Server Error: /api/v1/router-command/router_run_command/
Internal Server Error: /api/v1/router-command/router_run_command/
Internal Server Error: /api/v1/router-command/router_run_command/
Internal Server Error: /api/v1/router-command/router_run_command/
Internal Server Error: /api/v1/router-command/router_run_command/
Internal Server Error: /api/v1/router-command/router_run_command/
Internal Server Error: /api/v1/router-command/router_run_command/
Internal Server Error: /api/v1/router-command/router_run_command/
Internal Server Error: /api/v1/router-command/router_run_command/
Internal Server Error: /api/v1/router-command/router_run_command/
Internal Server Error: /api/v1/router-command/router_run_command/
Unauthorized: /api/v1/switch/get_backup_error_text/
Not Found: /api/v1/api/v1/router/
Bad Request: /api/v1/router/
Bad Request: /api/v1/router/
Internal Server Error: /api/v1/router/
Traceback (most recent call last):
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/mixins.py", line 40, in list
    page = self.paginate_queryset(queryset)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/generics.py", line 171, in paginate_queryset
    return self.paginator.paginate_queryset(queryset, self.request, view=self)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/pagination.py", line 196, in paginate_queryset
    page_size = self.get_page_size(request)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/pagination.py", line 257, in get_page_size
    return _positive_int(
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/pagination.py", line 30, in _positive_int
    return min(ret, cutoff)
TypeError: '<' not supported between instances of 'builtin_function_or_method' and 'int'
Not Found: /api/v1/router/router/
Internal Server Error: /api/v1/router/
Traceback (most recent call last):
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/mixins.py", line 40, in list
    page = self.paginate_queryset(queryset)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/generics.py", line 171, in paginate_queryset
    return self.paginator.paginate_queryset(queryset, self.request, view=self)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/pagination.py", line 196, in paginate_queryset
    page_size = self.get_page_size(request)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/pagination.py", line 257, in get_page_size
    return _positive_int(
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/rest_framework/pagination.py", line 30, in _positive_int
    return min(ret, cutoff)
TypeError: '<' not supported between instances of 'builtin_function_or_method' and 'int'
Internal Server Error: /api/v1/router
Traceback (most recent call last):
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 113, in __call__
    response = self.process_request(request)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/middleware/common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/middleware/common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:2080/api/v1/router/?page=1&page_size=10 (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
Bad Request: /api/v1/router/
Bad Request: /api/v1/router/
Bad Request: /api/v1/router/
Bad Request: /api/v1/router/
Bad Request: /api/v1/router/
Bad Request: /api/v1/router/
Bad Request: /api/v1/router/
Bad Request: /api/v1/router/
Bad Request: /api/v1/router/
Bad Request: /api/v1/switch/
Bad Request: /api/v1/switch/
Unauthorized: /api/v1/switch/get_backup_error_file/
Method Not Allowed: /api/v1/switch-command/
Unauthorized: /api/v1/switch/get_backup_error_file/
Method Not Allowed: /api/v1/switch/get_backup_error_file/
Method Not Allowed: /api/v1/switch-command/switch_run_command/
Not Found: /api/v1/switch-command/switch_run_command/
Not Found: /api/v1/api/v1/switch/switch_run_command/
Not Found: /favicon.ico
Internal Server Error: /admin/router/routercommand/
Traceback (most recent call last):
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/contrib/admin/options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1693, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/contrib/admin/options.py", line 735, in get_changelist_instance
    return ChangeList(
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/contrib/admin/views/main.py", line 99, in __init__
    self.queryset = self.get_queryset(request)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/contrib/admin/views/main.py", line 483, in get_queryset
    qs, search_use_distinct = self.model_admin.get_search_results(request, qs, self.query)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1028, in get_search_results
    queryset = queryset.filter(reduce(operator.or_, or_queries))
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/db/models/query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/db/models/query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/db/models/query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1237, in build_filter
    return self._add_q(
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1319, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1156, in build_lookup
    raise FieldError('Related Field got invalid lookup: {}'.format(lookup_name))
django.core.exceptions.FieldError: Related Field got invalid lookup: icontains
Internal Server Error: /admin/router/routercommand/
Traceback (most recent call last):
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/contrib/admin/options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1693, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/contrib/admin/options.py", line 735, in get_changelist_instance
    return ChangeList(
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/contrib/admin/views/main.py", line 99, in __init__
    self.queryset = self.get_queryset(request)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/contrib/admin/views/main.py", line 483, in get_queryset
    qs, search_use_distinct = self.model_admin.get_search_results(request, qs, self.query)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1028, in get_search_results
    queryset = queryset.filter(reduce(operator.or_, or_queries))
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/db/models/query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/db/models/query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/db/models/query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1237, in build_filter
    return self._add_q(
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1319, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1156, in build_lookup
    raise FieldError('Related Field got invalid lookup: {}'.format(lookup_name))
django.core.exceptions.FieldError: Related Field got invalid lookup: icontains
Internal Server Error: /admin/router/routercommand/
Traceback (most recent call last):
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/contrib/admin/options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1693, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/contrib/admin/options.py", line 735, in get_changelist_instance
    return ChangeList(
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/contrib/admin/views/main.py", line 99, in __init__
    self.queryset = self.get_queryset(request)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/contrib/admin/views/main.py", line 483, in get_queryset
    qs, search_use_distinct = self.model_admin.get_search_results(request, qs, self.query)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1028, in get_search_results
    queryset = queryset.filter(reduce(operator.or_, or_queries))
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/db/models/query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/db/models/query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/db/models/query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1237, in build_filter
    return self._add_q(
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1319, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/mrtbadboy/PycharmProjects/PortmanV3/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1156, in build_lookup
    raise FieldError('Related Field got invalid lookup: {}'.format(lookup_name))
django.core.exceptions.FieldError: Related Field got invalid lookup: icontains
Not Found: /
Internal Server Error: /api/v1/user/send_reset_password_link/
Internal Server Error: /api/v1/user/send_reset_password_link/
Internal Server Error: /api/v1/user/send_reset_password_link/
Unauthorized: /api/v1/user/send_reset_password_link/
Unauthorized: /api/v1/user/send_reset_password_link/
Unauthorized: /api/v1/user/send_reset_password_link/
Unauthorized: /api/v1/user/send_reset_password_link/
Unauthorized: /api/v1/users/send_reset_password_link/
Unauthorized: /api/v1/users/send_reset_password_link/
Unauthorized: /api/v1/users/send_reset_password_link/
Unauthorized: /api/v1/users/login/
Unauthorized: /api/v1/users/send_reset_password_link/
Method Not Allowed: /api/v1/users/send_reset_password_link/
Method Not Allowed: /api/v1/users/send_reset_password_link/
Method Not Allowed: /api/v1/users/send_reset_password_link/
Internal Server Error: /api/v1/dslamport/get_port_count/
Internal Server Error: /api/v1/router-command/router_run_command/
Internal Server Error: /api/v1/router-command/router_run_command/
Internal Server Error: /api/v1/router-command/router_run_command/
Internal Server Error: /api/v1/router-command/router_run_command/
Internal Server Error: /api/v1/router-command/router_run_command/
Internal Server Error: /api/v1/router-command/router_run_command/
Internal Server Error: /api/v1/router-command/router_run_command/
Internal Server Error: /api/v1/router-command/router_run_command/
Internal Server Error: /api/v1/router-command/router_run_command/
Internal Server Error: /api/v1/router-command/router_run_command/
Not Found: /favicon.ico
Internal Server Error: /api/v1/router-command/router_run_command/
Internal Server Error: /api/v1/router-command/router_run_command/
Internal Server Error: /api/v1/router-command/router_run_command/
Internal Server Error: /api/v1/router-command/router_run_command/
Internal Server Error: /api/v1/router-command/router_run_command/
Internal Server Error: /api/v1/router-command/router_run_command/
Internal Server Error: /api/v1/router-command/router_run_command/
Internal Server Error: /api/v1/router-command/router_run_command/
Internal Server Error: /api/v1/router-command/router_run_command/
Internal Server Error: /api/v1/router-command/router_run_command/
Not Found: /api/v1/router-comm/read_router_backup_error_files_name/
Method Not Allowed: /api/v1/router-command/read_router_backup_error_files_name/
Not Found: /favicon.ico
Not Found: /static/rest_framework/img/grid.png
Unauthorized: /api/v1/router-command/read_router_backup_error_files_name/
Unauthorized: /api/v1/router-command/read_router_backup_error_files_name/
Method Not Allowed: /api/v1/router-command/read_switch_backup_error_files_name/
Not Found: /static/rest_framework/css/bootstrap.min.css
Not Found: /static/rest_framework/css/bootstrap-tweaks.css
Not Found: /static/rest_framework/css/default.css
Not Found: /static/rest_framework/css/prettify.css
Not Found: /favicon.ico
Not Found: /static/admin-lte/dist/img/avatar5.png
Not Found: /static/admin-lte/dist/img/AdminLTELogo.png
Not Found: /static/admin-lte/plugins/fontawesome-free/css/all.min.css
Not Found: /static/admin-lte/plugins/icheck-bootstrap/icheck-bootstrap.min.css
Not Found: /static/admin/css/base.css
Not Found: /static/admin-lte/dist/css/adminlte.min.css
Not Found: /static/admin-lte/plugins/jquery/jquery.min.js
Not Found: /static/admin-lte/plugins/jquery-ui/jquery-ui.min.js
Not Found: /static/admin-lte/plugins/bootstrap/js/bootstrap.bundle.min.js
Not Found: /static/admin-lte/dist/js/adminlte.min.js
Not Found: /static/admin-lte/dist/js/demo.js
Not Found: /static/admin-lte/plugins/jquery-ui/jquery-ui.min.js
Not Found: /static/admin-lte/plugins/bootstrap/js/bootstrap.bundle.min.js
Not Found: /static/admin-lte/dist/js/adminlte.min.js
Not Found: /static/admin-lte/dist/js/demo.js
Not Found: /static/admin-lte/plugins/fontawesome-free/css/all.min.css
Not Found: /static/admin-lte/plugins/icheck-bootstrap/icheck-bootstrap.min.css
Not Found: /static/admin/css/base.css
Not Found: /static/admin-lte/dist/css/adminlte.min.css
Not Found: /static/admin-lte/plugins/jquery/jquery.min.js
Not Found: /static/admin-lte/dist/img/AdminLTELogo.png
Not Found: /static/admin-lte/plugins/bootstrap/js/bootstrap.bundle.min.js
Not Found: /static/admin-lte/dist/img/avatar5.png
Not Found: /static/admin-lte/plugins/jquery-ui/jquery-ui.min.js
Not Found: /static/admin-lte/dist/js/demo.js
Not Found: /static/admin-lte/dist/js/adminlte.min.js
Not Found: /static/admin-lte/dist/js/adminlte.min.js
Not Found: /static/admin-lte/dist/js/demo.js
Not Found: /static/admin-lte/plugins/fontawesome-free/css/all.min.css
Not Found: /static/admin/css/base.css
Not Found: /static/admin-lte/plugins/icheck-bootstrap/icheck-bootstrap.min.css
Not Found: /static/admin-lte/dist/css/adminlte.min.css
Not Found: /static/admin/css/changelists.css
Not Found: /static/admin/js/vendor/jquery/jquery.min.js
Not Found: /static/admin/js/jquery.init.js
Not Found: /static/admin/js/urlify.js
Not Found: /static/admin/js/core.js
Not Found: /static/admin/js/admin/RelatedObjectLookups.js
Not Found: /static/admin/js/actions.min.js
Not Found: /static/admin/js/prepopulate.min.js
Not Found: /static/admin/js/vendor/xregexp/xregexp.min.js
Not Found: /static/admin-lte/plugins/jquery/jquery.min.js
Not Found: /static/admin-lte/plugins/jquery-ui/jquery-ui.min.js
Not Found: /static/admin-lte/plugins/datatables-bs4/css/dataTables.bootstrap4.css
Not Found: /static/admin-lte/plugins/bootstrap/js/bootstrap.bundle.min.js
Not Found: /static/admin-lte/dist/js/adminlte.min.js
Not Found: /static/admin-lte/dist/js/demo.js
Not Found: /static/admin-lte/plugins/datatables-bs4/js/dataTables.bootstrap4.js
Not Found: /static/admin-lte/plugins/datatables/jquery.dataTables.js
Not Found: /static/admin-lte/dist/img/avatar5.png
Not Found: /static/admin-lte/dist/img/AdminLTELogo.png
Not Found: /static/admin/js/vendor/jquery/jquery.min.js
Not Found: /static/admin/js/jquery.init.js
Not Found: /static/admin/js/core.js
Not Found: /static/admin/js/admin/RelatedObjectLookups.js
Not Found: /static/admin/js/actions.min.js
Not Found: /static/admin/js/urlify.js
Not Found: /static/admin/js/prepopulate.min.js
Not Found: /static/admin/js/vendor/xregexp/xregexp.min.js
Not Found: /static/admin-lte/dist/img/avatar5.png
Not Found: /static/admin-lte/dist/img/AdminLTELogo.png
Not Found: /static/admin-lte/plugins/datatables-bs4/css/dataTables.bootstrap4.css
Not Found: /static/admin-lte/plugins/jquery/jquery.min.js
Not Found: /static/admin-lte/plugins/jquery-ui/jquery-ui.min.js
Not Found: /static/admin-lte/plugins/bootstrap/js/bootstrap.bundle.min.js
Not Found: /static/admin-lte/dist/js/adminlte.min.js
Not Found: /static/admin-lte/dist/js/demo.js
Not Found: /static/admin-lte/plugins/datatables/jquery.dataTables.js
Not Found: /static/admin-lte/plugins/datatables-bs4/js/dataTables.bootstrap4.js
Not Found: /static/rest_framework/css/bootstrap.min.css
Not Found: /static/rest_framework/css/prettify.css
Not Found: /static/rest_framework/css/bootstrap-tweaks.css
Not Found: /static/rest_framework/css/default.css
Not Found: /favicon.ico
Not Found: /static/admin-lte/dist/img/avatar5.png
Not Found: /static/admin-lte/dist/img/AdminLTELogo.png
Not Found: /static/admin-lte/plugins/fontawesome-free/css/all.min.css
Not Found: /static/admin-lte/dist/css/adminlte.min.css
Not Found: /static/admin-lte/plugins/jquery/jquery.min.js
Not Found: /static/admin-lte/plugins/icheck-bootstrap/icheck-bootstrap.min.css
Not Found: /static/admin-lte/dist/js/adminlte.min.js
Not Found: /static/admin/css/base.css
Not Found: /static/admin-lte/dist/js/demo.js
Not Found: /static/admin-lte/plugins/bootstrap/js/bootstrap.bundle.min.js
Not Found: /static/admin-lte/plugins/jquery-ui/jquery-ui.min.js
Not Found: /static/admin-lte/plugins/jquery-ui/jquery-ui.min.js
Not Found: /static/admin-lte/plugins/bootstrap/js/bootstrap.bundle.min.js
Not Found: /static/admin-lte/dist/js/adminlte.min.js
Not Found: /static/admin-lte/dist/js/demo.js
Not Found: /static/admin-lte/plugins/fontawesome-free/css/all.min.css
Not Found: /static/admin-lte/dist/css/adminlte.min.css
Not Found: /static/admin-lte/plugins/icheck-bootstrap/icheck-bootstrap.min.css
Not Found: /static/admin/css/base.css
Not Found: /static/admin/js/vendor/jquery/jquery.min.js
Not Found: /static/admin/js/actions.min.js
Not Found: /static/admin/js/vendor/xregexp/xregexp.min.js
Not Found: /static/admin/js/prepopulate.min.js
Not Found: /static/admin-lte/plugins/jquery/jquery.min.js
Not Found: /static/admin-lte/plugins/jquery-ui/jquery-ui.min.js
Not Found: /static/admin-lte/plugins/bootstrap/js/bootstrap.bundle.min.js
Not Found: /static/admin-lte/dist/js/adminlte.min.js
Not Found: /static/admin-lte/dist/js/demo.js
Not Found: /static/admin/js/jquery.init.js
Not Found: /static/admin/css/changelists.css
Not Found: /static/admin/js/core.js
Not Found: /static/admin/js/admin/RelatedObjectLookups.js
Not Found: /static/admin/js/urlify.js
Not Found: /static/admin-lte/plugins/datatables-bs4/css/dataTables.bootstrap4.css
Not Found: /static/admin-lte/plugins/datatables/jquery.dataTables.js
Not Found: /static/admin-lte/plugins/datatables-bs4/js/dataTables.bootstrap4.js
Not Found: /static/admin-lte/dist/img/avatar5.png
Not Found: /static/admin-lte/dist/img/AdminLTELogo.png
Not Found: /static/admin/js/vendor/jquery/jquery.min.js
Not Found: /static/admin/js/jquery.init.js
Not Found: /static/admin/js/core.js
Not Found: /static/admin/js/admin/RelatedObjectLookups.js
Not Found: /static/admin/js/actions.min.js
Not Found: /static/admin/js/urlify.js
Not Found: /static/admin/js/prepopulate.min.js
Not Found: /static/admin/js/vendor/xregexp/xregexp.min.js
Not Found: /static/admin-lte/dist/img/avatar5.png
Not Found: /static/admin-lte/dist/img/AdminLTELogo.png
Not Found: /static/admin-lte/plugins/datatables-bs4/css/dataTables.bootstrap4.css
Not Found: /static/admin-lte/plugins/jquery/jquery.min.js
Not Found: /static/admin-lte/plugins/jquery-ui/jquery-ui.min.js
Not Found: /static/admin-lte/plugins/bootstrap/js/bootstrap.bundle.min.js
Not Found: /static/admin-lte/dist/js/adminlte.min.js
Not Found: /static/admin-lte/dist/js/demo.js
Not Found: /static/admin-lte/plugins/datatables/jquery.dataTables.js
Not Found: /static/admin-lte/plugins/datatables-bs4/js/dataTables.bootstrap4.js
Not Found: /
Not Found: /
Not Found: /static/admin-lte/plugins/fontawesome-free/css/all.min.css
Not Found: /static/admin-lte/dist/css/adminlte.min.css
Not Found: /static/admin-lte/plugins/icheck-bootstrap/icheck-bootstrap.min.css
Not Found: /static/admin/css/base.css
Not Found: /static/admin-lte/plugins/jquery-ui/jquery-ui.min.js
Not Found: /static/admin-lte/plugins/bootstrap/js/bootstrap.bundle.min.js
Not Found: /static/admin-lte/plugins/jquery/jquery.min.js
Not Found: /static/admin-lte/dist/img/avatar5.png
Not Found: /static/admin-lte/dist/js/adminlte.min.js
Not Found: /static/admin-lte/dist/img/AdminLTELogo.png
Not Found: /static/admin-lte/dist/js/demo.js
Not Found: /static/admin-lte/plugins/bootstrap/js/bootstrap.bundle.min.js
Not Found: /static/admin-lte/dist/js/adminlte.min.js
Not Found: /static/admin-lte/dist/js/demo.js
Not Found: /
>>>>>>> bed75979233d1a54abeaafc17941b9e5e3eb3ab1
Unauthorized: /api/v1/router/download_router_backup_file/
Unauthorized: /api/v1/router/download_router_backup_file/
Unauthorized: /api/v1/dslam-port/
Unauthorized: /api/v1/switch/
Unauthorized: /api/v1/router/
Unauthorized: /api/v1/switch/
Unauthorized: /api/v1/router/get_router_backup_files_name/
Unauthorized: /api/v1/router/
Unauthorized: /api/v1/dslam/
Unauthorized: /api/v1/users/get_permission/
Unauthorized: /api/v1/dslam/get_interface_traffic_input/
Unauthorized: /api/v1/dslamport/events/
Unauthorized: /api/v1/dslam/get_dslams_packet_loss_count/
Unauthorized: /api/v1/dslam/events/
Unauthorized: /api/v1/telecom-center/
Unauthorized: /api/v1/contact/portmap/
Unauthorized: /api/v1/telecom-center/
Unauthorized: /api/v1/router/
Unauthorized: /api/v1/dslam/
Unauthorized: /api/v1/telecom-center/
Unauthorized: /api/v1/router/
Unauthorized: /api/v1/router/
Unauthorized: /api/v1/router/
Unauthorized: /api/v1/router/
Unauthorized: /api/v1/dslam/
Unauthorized: /api/v1/router/
Unauthorized: /api/v1/router/
Unauthorized: /api/v1/switch/
Unauthorized: /api/v1/router/
